version: '2.1'
services:
  backend-web:
    image: maven:3.3.9-jdk-8
    volumes:
      - ./:/usr/src/app
      - ~/.m2:/root/.m2
    ports:
      - "8080"
      - "8081"
    working_dir: /usr/src/app
    entrypoint: >
      bash -c "mvn package -DskipTests &&
      java -jar target/dropwizard-basic-1.0-SNAPSHOT.jar db migrate config.yml &&
      java -jar target/dropwizard-basic-1.0-SNAPSHOT.jar server config.yml"
    healthcheck:
      test: curl --fail --location http://localhost:8081/ping
      interval: 30s
      timeout: 5s
      retries: 20
    depends_on:
      backend-db:
        condition: service_healthy

  ##################################################

  backend-db: #https://hub.docker.com/_/mysql/
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=dropwizard_basic
    healthcheck:
      test: echo 'SELECT 1' | mysql --user="root" > /dev/null
      interval: 15s
      timeout: 5s
      retries: 4
    ports:
      - "3306"
